# Generated by Django 4.1.1 on 2022-09-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Required. 500 characters or fewer.', max_length=500, verbose_name='description')),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('C', 'Complete'), ('TD', 'To Do'), ('PD', 'Past Due')], default='TD', max_length=25)),
                ('todo_by', models.DateTimeField(verbose_name='todo by date')),
                ('completed_at', models.DateTimeField(verbose_name='completed at date')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'abstract': False,
            },
        ),
    ]
