# Generated by Django 4.1.1 on 2022-10-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completed_at',
            field=models.DateTimeField(null=True, verbose_name='completed at date'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todo_by',
            field=models.DateTimeField(null=True, verbose_name='todo by date'),
        ),
    ]
