# Generated by Django 4.1.1 on 2022-10-01 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_backend', '0002_alter_todoitem_completed_at_alter_todoitem_todo_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
